### ISSUE TITLE
Yaml config source generates strings from yaml lists not compatible with MicroProfile Config array conversion rules

### ISSUE THREAD

**Issue by chrismanning** [microprofile-extensions/config-ext#10]
When a yaml list is present in a config source `YamlConfigSource` generates a String as "[item1, item2]" making it incompatible with the list format expected by MicroProfile Config array converters. I expected this to work with MicroProfile Config such that I could inject a list value into a `List<String>` and it would place the individual values into different elements.

See https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/converters.asciidoc#array-converters

**Comment by phillip-kruger** [comment]
Can you provide an example yaml file ?

**Comment by chrismanning** [comment]
Example yaml:
```yaml
listTest:
  - item1
  - item2
```
Injecting:
```java
@Inject
@ConfigProperty(name = "listTest")
String listTest; // "[item1, item2]"

@Inject
@ConfigProperty(name = "listTest")
List<String> listTest2; // ["[item1, item2]"]
```

**Comment by phillip-kruger** [comment]
Thanks, I'll look at this soon.

**Comment by phillip-kruger** [comment]
@chrismanning please check if PR #11 is working for you. I merged the changes and released v 1.0.8, it should be available in maven central soon.

Also have a look at the new test case called `ListTest`

Let me know so that I can close the issue.

**Comment by phillip-kruger** [comment]
@chrismanning - OK you should now use v 1.0.9, I fixed an issue where if you add a comma to the element in the list it treated it as a new element. Fixed in 1.0.9. I also added this fix to JSON and XML converters as the same issue existed there. Let me know.

**Comment by phillip-kruger** [comment]
OK it's available in Maven central

https://search.maven.org/artifact/org.microprofile-ext.config-ext/configsource-yaml/1.0.9/jar

```
<dependency>
  <groupId>org.microprofile-ext.config-ext</groupId>
  <artifactId>configsource-yaml</artifactId>
  <version>1.0.9</version>
</dependency>
```

**Comment by phillip-kruger** [comment]
@chrismanning Any feedback ?

**Comment by phillip-kruger** [comment]
No feedback. Closing. @chrismanning please reopen if you still have issues
