### ISSUE TITLE
merging with smallrye

### ISSUE THREAD

**Issue by phillip-kruger** [microprofile-extensions/config-ext#15]
Hi all.
(@rikcarve , @derekm , @enoren)

Since you all contributed to this project, please reply here.

We have an opportunity to merge with smallrye. The smallrye community is active and is a full implementation of MicroProfile and some extentions. The plan would be to donate all code from MicroProfile-ext to smallrye and continue to contribute there.

 I am already contributing to Smallrye, and for me to continue to work on Microprofile-ext, it would make sense to move. Most of the code in this project is written by me, but I want to get your input as well. I am for it and think this is the best for the community.

Please let me know your vote a.s.a.p.

**Comment by phillip-kruger** [comment]
B.t.w, smallrye is independent of any runtime, and can be use, both from an implementation point of view, and the extensions, by any runtime. Example OpenLiberty, Thorntail, Quarkus etc.

We will keep the code as is here, with a notice that it's moved. So users that use the current libraries will continue to do so, however, when updating to the latest version they also update the artifactId.

Ok please let me know. Yes or no

**Comment by rikcarve** [comment]
I would be more than happy to contribute this code to the smallrye project. So it's a yes from my side

**Comment by phillip-kruger** [comment]
@rikcarve thanks for the feedback

**Comment by derekm** [comment]
For the record, SmallRye is an implementation of MicroProfile, so we need to ensure MP-Ext remains independent of any implementation of MicroProfile.

I may already be running into differences between Geronimo Config and SmallRye Config.

**Comment by derekm** [comment]
I'm a yes, but I want to pursue all options that prevent breaking early adopters of MP-Ext.

Believe it or not, we have code running in production, and the responsible thing is to prevent breaking our users.

I don't believe we've yet to adequately consider how the projects can be merged in a way that preserves the code and repos mostly unchanged.

**Comment by phillip-kruger** [comment]
All code in production will obvious still run as is. All versions before the donation will still be here and will still be available in Maven Central.

If someone wants to use a newer version, rather than just updating the version number, they also now update the groupId.

In many cases that would be all. If they are using the events, some imports of package names might also change.

So not a big issue in my mind.

**Comment by phillip-kruger** [comment]
W.r.t differences between Geronimo Config and SmallRye Config:

That is (possibly) an existing issue anyway and whether we are part of Smallrye or not, it's something we need to solve. Right ?

**Comment by derekm** [comment]
Talking with Ken Finnigan, it sounded like they were only familiar with `config-ext`'s config sources and haven't put much thought into the rest of MP-Ext yet. Does this impact all MP-Ext repos or only `config-ext`?

@phillip-kruger, I like your suggestion that only groupIds and package name prefixes will change with a massive search and replace to favor "io.smallrye". This implies that the repo(s) will move over essentially unchanged. Is that also your take?

Btw, I forgot I'd already solved the MP Config impl differences in `config-ext` itself by using `ConfigProviderResolver` instead of using `ConfigProvider.getConfig()` like SmallRye does.

**Comment by phillip-kruger** [comment]
I will check with Ken w.r.t other non-config projects. The donation should be as-is, with the exception of groupId and package name changes, at least initially.
Then the projects will evolve under Smallrye and might/might not make more changes as it would now with new versions.

**Comment by phillip-kruger** [comment]
I just got some feedback, the plan is to donate everything, not splitting the current microrprofile-ext community and projects.

**Comment by kenfinnigan** [comment]
I can confirm that the idea from the SmallRye side was that everything was donated, as it would be great to combine forces

**Comment by phillip-kruger** [comment]
Thanks @kenfinnigan !

**Comment by enoren** [comment]
No issue from me. Thanks!

**Comment by phillip-kruger** [comment]
Ok, thanks all. We had feedback from everyone. I am closing this and we will get the process to move started. If you have any fixes / updates in the pipeline, let's hold off until after the move.

**Comment by chester89** [comment]
hello. can I ask - was the merge successful? I'm very much interested in consul source for openrye
