### ISSUE TITLE
Changes in source file only detected once

### ISSUE THREAD

**Issue by cbos** [microprofile-extensions/config-ext#17]
I have set 3 properties:
configsource.yaml.pollForChanges=true;
configsource.yaml.pollInterval=30;
configsource.yaml.url=file:/E:/app/settings.yaml

Once the application is started, and I make changes, is detected right away.
But a new changes it not detected anymore.

When I look to the code the pollInterval is only use to schedule the first check.
Then it keeps looping, which might overtime result in a stackoverflow, as the this.run call is recursive.

**Comment by phillip-kruger** [comment]
Hi

I can't manage to recreate your problem. Can you use the example app in config-example to recreate the issue ?

See below:
![live_reload](https://user-images.githubusercontent.com/6836179/58936561-509c0580-8770-11e9-85ed-98e8c84f2388.gif)

**Comment by phillip-kruger** [comment]
@cbos - any more details ? Can you recreate the issue in the example app so that I can have a look ?

**Comment by cbos** [comment]
@phillip-kruger 
I will spend some time to provide more information, I will update once I have that.

**Comment by cbos** [comment]
I have started some debugging.
I noticed that the update was detected and handled and then update keeps hanging.
I managed to the updates, by adding the setting: configsource.yaml.notifyOnChanges=false 
Without setting this property it is not working on TomEE 8.0.0-M3

The changes are detected immediately, there is nothing done with the poller interval.
And the stack keeps growing:
![image](https://user-images.githubusercontent.com/255404/59036663-039f5880-8870-11e9-8190-f9f3f6e00ac8.png)

**Comment by phillip-kruger** [comment]
Ok, so can you get the update now (when you switch off the CDI events ?)
Can you test this on another application server (like Thorntail or Payara or OpenLiberty)
Then we can figure out if this is a bug specific to TomEE or in general. Do you have a fix in mind ?

**Comment by phillip-kruger** [comment]
There should only be one poller per directory to scan, so not sure why you see this behaviour, again I can not recreate it, but the code below is suppose to stop that from happening. Maybe you can spot the bug
![Screenshot_20190614_162801-1](https://user-images.githubusercontent.com/6836179/59516412-9455e400-8ec1-11e9-8cd7-6216a0f7b68d.png)

**Comment by phillip-kruger** [comment]
@cbos can you please checkout and build from source and then test 1.0.10-SNAPSHOT in your example. I added a possible fix for the creation of new threads, that I would like you to validate.
Thanks
