### ISSUE TITLE
Cannot deploy configsource-properties in payara 5.192

### ISSUE THREAD

**Issue by markusweisssiemens** [microprofile-extensions/config-ext#18]
Hi, 

I'm always getting a CDI Exception if I try to deploy my application with the dependency to configsource-properties. I created a very small test project which reproduces this error:
[configexttest.zip](https://github.com/microprofile-extensions/config-ext/files/3267019/configexttest.zip)
I've also attached the extract of the log (
[serverlog.txt](https://github.com/microprofile-extensions/config-ext/files/3264919/serverlog.txt)
) which shows the stacktrace. Am I missing something or is this a bug?

I'm using payara server full.

I've updated the example with an Arquillian test which reproduces the behaviour:
[configexttest.zip](https://github.com/microprofile-extensions/config-ext/files/3267019/configexttest.zip)

**Comment by phillip-kruger** [comment]
Hi @markusweisssiemens - I am looking at this now, will get back to you a.s.a.p

**Comment by phillip-kruger** [comment]
Hi @markusweisssiemens - do you get this error when running the ConfigurationServiceIT test ? Can you share your config file as well please ?

**Comment by markusweisssiemens** [comment]
Hi @phillip-kruger - yes I get this error when running the ConfigurationServiceIT test. I've tried adding a microprofile-config.properties to src/test/resources/META-INF folder (see 
[props.zip](https://github.com/microprofile-extensions/config-ext/files/3274928/props.zip)) and adding the application.properties to my windows D:/temp dir but I get the same error.

**Comment by phillip-kruger** [comment]
Hi @markusweisssiemens - I can not recreate the error. My tests pass (even with the properties as above). I am wondering if it's a windows thing ? (As I run Linux). Sorry, trying to help, but not sure how to proceed if I can not recreate the issue. What worries me is that it seems like you can read the file ?

![image](https://user-images.githubusercontent.com/6836179/59251814-fc3ecd00-8c2a-11e9-8673-8f0e83d6fea0.png)
![image](https://user-images.githubusercontent.com/6836179/59251870-1c6e8c00-8c2b-11e9-9c7f-60f102813266.png)
![image](https://user-images.githubusercontent.com/6836179/59251957-4a53d080-8c2b-11e9-9146-763053b2716d.png)

Would you be able to debug some more ? Maybe try and add the application.properties on the default location (the root of your project)

**Comment by markusweisssiemens** [comment]
Hi @phillip-kruger - I've attached my logfile: 
[logfile.zip](https://github.com/microprofile-extensions/config-ext/files/3275569/logfile.zip). This log is from the test execution where I don't configure the file location and added the application.properties file directly in the root of the project. But still I got the error. It's the same error once I configure another path and use this other path.

**Comment by phillip-kruger** [comment]
Hi @markusweisssiemens - simple question (as I can still not recreate the issue). If you remove microprofile-ext's config-ext totally, does it work ? (I.e just use the build in config source providers)

**Comment by markusweisssiemens** [comment]
Hi @phillip-kruger - as soon as I remove the dependency for the configsource-properties (configsource-ext) the test is running and successfully executed.

**Comment by phillip-kruger** [comment]
Hi @markusweisssiemens - Damm, ok, I have no idea how to proceed if I can not recreate the issue. Can you maybe try on another implementation like OpenLiberty or Thorntail ? (Just to help with the debug)

**Comment by phillip-kruger** [comment]
Hi @markusweisssiemens - also please try the example https://github.com/microprofile-extensions/config-ext/tree/master/config-example and let me know. The example makes it easy to test with payara, thorntail and openliberty
