### ISSUE TITLE
Microprofile 4.0 update

### ISSUE THREAD

**Issue by sergey-morenets** [microprofile-extensions/config-ext#25]
Hi

It seems that current version of Microprofile extensions are still aligned with Microprofile 2.2.
Are there any plans to update to the latest version?

**Comment by phillip-kruger** [comment]
Yes !! And any help on this would be appreciated :)

**Comment by sergey-morenets** [comment]
@phillip-kruger  How can I help? Make source code changes and create pull request?

**Comment by phillip-kruger** [comment]
That will help !!

**Comment by rikcarve** [comment]
A simple solution would be to add the former default implementation of getPropertyNames() to the BaseConfigSource as in my commit above.
Of course, we should also update the dependencies...

**Comment by phillip-kruger** [comment]
Thanks for the fix @rikcarve .
I'll see if I can update the dependencies, and then we can do a major release.
