### ISSUE TITLE
configsource-yaml: NullPointerException (NPE) when existing yaml-configuration-file is empty

### ISSUE THREAD

**Issue by ghost** [microprofile-extensions/config-ext#33]
When loading an empty yaml-file the SnakeYAML library return null when using the method loadAs(Reader io, Class<T> type) and producing a NullPointerException on yamlInput.keySet() in the line 
https://github.com/microprofile-extensions/config-ext/blob/80f6bf0a904c867ef63c754aa8ae4c0d8217d1ce/configsource-yaml/src/main/java/org/microprofileext/config/source/yaml/YamlConfigSource.java#L31

The behavior of SnakeYAML makes sense for de-serialization.
Non-null should be checked before the mentioned line of configsource-yaml.

**Comment by phillip-kruger** [comment]
Thanks @iWitzky . Your fix is merged. Do you need a release ?

**Comment by ghost** [comment]
@phillip-kruger A release would be nice. Thanks!

**Comment by phillip-kruger** [comment]
Hi @iWitzky  version 2.0.1 is out. Thanks :)
