### ISSUE TITLE
Microprofile 5.0 and jakarta support

### ISSUE THREAD

**Issue by vincent-nagy** [microprofile-extensions/config-ext#40]
Hi

Could you confirm that this library has no support for microprofile 5.0 and jakarta 9.1?

I'm getting this error:
[INFO] [INFO    ] WELD-000119: Not generating any bean definitions from org.microprofileext.config.event.ChangeEventNotifier because of underlying class loading error: Type javax.enterprise.event.Event not found.  If this is unexpec
ted, enable DEBUG logging to see the full error.

**Comment by phillip-kruger** [comment]
Yes, we still need to do the jakarta namespace change. PRs welcome :)

**Comment by tmonney** [comment]
Hello,

I gave it a shot. I tested it locally (the in-memory config source at least) in our Quarkus 3.0 application and there it seems to be working fine.

Cheers
Thierry
